PACKAGE_NAME="audioreach-dkms"
PACKAGE_VERSION="1.1.0"
BUILT_MODULE_NAME[0]="audioreach_driver"
BUILT_MODULE_LOCATION[0]="audioreach-driver"
DEST_MODULE_LOCATION[0]="/extra/audioreach-dkms"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL_MIN="6.18"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/audioreach-driver modules VENDOR_QCOM=1"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/audioreach-driver clean"
